### ISSUE TITLE
unable to complete the setup

### ISSUE THREAD

**Issue by yzbbbbb** [Aldo796/BDSP-Randomizers#14]
![image](https://user-images.githubusercontent.com/96726675/147469043-9cd37c83-bf8a-4924-9e4b-25ce68716ee5.png)

 any idea on how to fix this ?

**Comment by Ai0796** [comment]
you should probably redownload, that's an error with a txt file that probably was corrupted somewhere

**Comment by Greenertia** [comment]
Having a similar issue but with cp949 codec. I've tried redownloading and using previous versions but it keeps coming up with the same issue. 
![image](https://user-images.githubusercontent.com/96873257/147753792-d11745a8-3bdf-466f-8eae-6acf41f0d3c5.png)

**Comment by sora1614** [comment]
Same issue but mine says "cp932" and redownloading did not help.

**Comment by sora1614** [comment]
RomFS Directory set to C:/Users/kapla/Downloads/exe.win-amd64-3.9/romfs
Randomizing Starters!
An Error has occured: 
Traceback (most recent call last):
  File "main.py", line 38, in buttonClicked
  File "D:\Users\moald\OneDrive\Projects\BDSP-Randomizers\Randomizers\Starters.py", line 135, in RandomizeStarters
  File "D:\Users\moald\OneDrive\Projects\BDSP-Randomizers\Randomizers\Starters.py", line 113, in colorPokemon
  File "D:\Users\moald\OneDrive\Projects\BDSP-Randomizers\Randomizers\Starters.py", line 96, in getPokemonColor
UnicodeDecodeError: 'cp932' codec can't decode byte 0x82 in position 5699: illegal multibyte sequence

**Comment by sora1614** [comment]
I've redownloaded the randomizer several times and it always gives me the same error.

**Comment by Greenertia** [comment]
Figured out what the issue was @yzbbbbb @sora1614 
The error stems from python 3 using locale default encoding instead of UTF-8, all you need to do it temporarily change your default locale language to english, run the randomiser, and change it back if you want to. 

Open control panel -> go to region -> administrative tab at the top -> and then change language of non-unicode programs to english. It will require admin and might require you to restart your computer.

Edit: Nevermind, looks like if you want starters randomised, you need to keep your system locale language to english. On the bright side, once your computer has a language downloaded, you won't need to restart your computer every time you swap it so it's easy to swap back and forth between english and whatever language you use.

**Comment by sora1614** [comment]
That worked. Apparently I had it set to japanese for some reason.

**Comment by sora1614** [comment]
Now the game freeze's on the menu where I pick the language.

**Comment by sora1614** [comment]
The fps just drops to 0.

**Comment by sora1614** [comment]
So I downgraded my game to 1.1.2 and everything works just fine.

**Comment by noah1gamble** [comment]
> So I downgraded my game to 1.1.2 and everything works just fine.

How did you do this?

**Comment by sora1614** [comment]
I actually forgot to mention that I went back to the old randomizer as well. To downgrade the game version right click on the game then go to remove and then click remove installed updates. From there just download an old update and install it.

**Comment by sora1614** [comment]
I got the randomizer set up to work but I'm still having problems in game so I don't know how helpful this info will be.

**Comment by noah1gamble** [comment]
> I got the randomizer set up to work but I'm still having problems in game so I don't know how helpful this info will be.

I haven't gotten it to work over the 10+ times I've tried in the past few weeks, I do it all correctly and the game simply refuses to start, so Idk. I've looked it up, followed anything, installed some mod managers, nothing, Idk, not worth it at this point I guess.
