### ISSUE TITLE
exefs not working in atmosphere

### ISSUE THREAD

**Issue by Killertube** [Aldo796/BDSP-Randomizers#24]
Dear,

I play pokemon bd on version 1.1.1 but when i put the exefs file in folder of pokemon it wont randomize my starter pokemon.
it shows the randomized name but when i trow the pokeball i get a normal starter.

Thanks in advance.

**Comment by Ai0796** [comment]
Try the new update, version 2.7

**Comment by Killertube** [comment]
Sorry that was not the solution, still have the same problem.

**Comment by Ai0796** [comment]
can you send a picture of the exefs folder

**Comment by Senexis** [comment]
@Ai0796 Hey there, am having the same issue as this person. SP, 1.1.1, names randomized but Pokémon aren't randomized. Here's the screenshots:

**The main folder in atmosphere/contents/:**
![image](https://user-images.githubusercontent.com/6360733/149783195-495186a9-7f01-4c3f-9e14-d8119ac45f0a.png)

**The exefs folder of the title:**
![image](https://user-images.githubusercontent.com/6360733/149783252-3bcdf075-b9ab-439a-93f3-774ef6c0642f.png)

Hope that helps in diagnosing the issue!

**Comment by Senexis** [comment]
@Ai0796 @Killertube Figured it out. To get starter randomization to work on Atmosphere, instead of putting the **exefs** folder in `atmosphere/contents/<title>/`, rename the folder into something you'll recognize later (I renamed the folder to **pokemon_sp_randomize_starters**) and place it in `atmosphere/exefs_patches/`.

If everything goes right, your **exefs_patches** folder should look like this:
![image](https://user-images.githubusercontent.com/6360733/149793762-9bddb62b-755b-4332-999d-5252bdf0f0bb.png)
**Note:** Inside the **pokemon_sp_randomize_starters** folder, there should be no subfolder, so it'll just be the IPA patch files.

And your **contents** folder should look like this:
![image](https://user-images.githubusercontent.com/6360733/149793830-9618f316-1676-496b-9208-298766c9affb.png)

Afterwards, you'll have randomized starters in BDSP on Atmosphere!

**Comment by Killertube** [comment]
sorry for the late response i just use a save modifier for my problem but i will try it on a new account thanks

**Comment by Ai0796** [comment]
https://github.com/Ai0796/BDSP-Randomizers/releases/tag/v2.9.0 Try the new release, it should contain all the files necessary for atmosphere

**Comment by Senexis** [comment]
> https://github.com/Ai0796/BDSP-Randomizers/releases/tag/v2.9.0 Try the new release, it should contain all the files necessary for atmosphere

Works fine for me. Deleted all other files to test, copied the generated **atmosphere** to my SD root, and all good!
